# This page was generated by Django using the inspectdb command in manage.py. That command examines the
# childfrontiers database and performs an ORM procedure to create model objects of each database table. Models are
# created in models.py

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('data_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('data_source_type', models.CharField(blank=True, max_length=19, null=True)),
                ('aquisition_date', models.DateField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('community', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'data_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=43)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'employee_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_type', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('project_type', models.CharField(blank=True, max_length=20, null=True)),
                ('completion_type', models.DateField()),
                ('country', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=255)),
                ('question_rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionVignette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'question_vignette',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualitative_response', models.CharField(max_length=255)),
                ('quantitative_response', models.IntegerField()),
                ('boolean_response', models.IntegerField()),
            ],
            options={
                'db_table': 'response',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('vignette_id', models.AutoField(primary_key=True, serialize=False)),
                ('vignette_type', models.CharField(blank=True, max_length=19, null=True)),
                ('vignette_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'vignette',
                'managed': False,
            },
        ),
    ]
