from django.db import migrations, models


# This class was generated by Django using the makemigrate command in manage.py. That command examines the
# data models in models.py and creates the Migration class to update database tables to match the models.
class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': True,
                'ordering': ('name',)
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=20, blank=False, null=False)),
                ('completion_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('client', models.ForeignKey(to='UI.Client', null=False, on_delete=models.CASCADE)),
            ],
            options={
                'db_table': 'project',
                'managed': True,
                'ordering': ('name',)
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('data_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('data_source_type', models.CharField(blank=True, max_length=19, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(to='UI.Project', null=False, on_delete=models.CASCADE)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('community', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'data_source',
                'managed': True,
                'ordering': ('name',)
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=43)),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
                'ordering': ('last_name',)
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_type', models.CharField(blank=False, max_length=30, null=False)),
            ],
            options={
                'db_table': 'participant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=255, blank=False, null=False)),
                ('question_rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualitative_response', models.CharField(max_length=255)),
                ('quantitative_response', models.IntegerField(blank=True, null=True)),
                ('boolean_response', models.PositiveIntegerField(blank=True, null=True)),
                ('participant', models.ForeignKey(to='UI.Participant', null=False, on_delete=models.CASCADE)),
                ('question', models.ForeignKey(to='UI.Question', null=False, on_delete=models.CASCADE)),
                ('data_source', models.ForeignKey(to='UI.DataSource', null=False, on_delete=models.CASCADE)),
            ],
            options={
                'db_table': 'response',
                'managed': True,
                'ordering': ('response_id',)
            },
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('vignette_id', models.AutoField(primary_key=True, serialize=False)),
                ('vignette_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vignette_description', models.CharField(blank=False, max_length=200, null=False)),
            ],
            options={
                'db_table': 'vignette',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionVignette',
            fields=[
                ('question', models.ForeignKey(to='UI.Question', null=False, on_delete=models.CASCADE)),
                ('vignette', models.ForeignKey(to='UI.Vignette', null=False, on_delete=models.CASCADE)),
            ],
            options={
                'db_table': 'question_vignette',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectDataSourceEmployee',
            fields=[
                ('project', models.ForeignKey(to='UI.Project', null=False, on_delete=models.CASCADE)),
                ('data_source', models.ForeignKey(to='UI.DataSource', null=False, on_delete=models.CASCADE)),
                ('employee', models.ForeignKey(to='UI.Employee', null=False, on_delete=models.CASCADE)),
            ],
            options={
                'db_table': 'project_data_source_employee',
                'managed': True,
            },
        ),
    ]
